minor upd
SVN-Revision: 66872

diff --git a/statistics/support/libs/assign/v2/test/unit_testing/log_ubuntu_gcc44_0x b/statistics/support/libs/assign/v2/test/unit_testing/log_ubuntu_gcc44_0x
--- a/statistics/support/libs/assign/v2/test/unit_testing/log_ubuntu_gcc44_0x
+++ b/statistics/support/libs/assign/v2/test/unit_testing/log_ubuntu_gcc44_0x
@@ -1,20 +1,9 @@
 11/29/10
+cxxflags=-std=c++0x
 ...patience...
 ...patience...
 ...found 1536 targets...
 ...updating 32 targets...
-gcc.compile.c++ ../../../../../bin.v2/libs/assign/v2/test/unit_testing/type_traits.test/gcc-4.4.3/debug/type_traits.o
-gcc.link ../../../../../bin.v2/libs/assign/v2/test/unit_testing/type_traits.test/gcc-4.4.3/debug/type_traits
-testing.capture-output ../../../../../bin.v2/libs/assign/v2/test/unit_testing/type_traits.test/gcc-4.4.3/debug/type_traits.run
-**passed** ../../../../../bin.v2/libs/assign/v2/test/unit_testing/type_traits.test/gcc-4.4.3/debug/type_traits.test
-gcc.compile.c++ ../../../../../bin.v2/libs/assign/v2/test/unit_testing/detail.test/gcc-4.4.3/debug/detail.o
-gcc.link ../../../../../bin.v2/libs/assign/v2/test/unit_testing/detail.test/gcc-4.4.3/debug/detail
-testing.capture-output ../../../../../bin.v2/libs/assign/v2/test/unit_testing/detail.test/gcc-4.4.3/debug/detail.run
-**passed** ../../../../../bin.v2/libs/assign/v2/test/unit_testing/detail.test/gcc-4.4.3/debug/detail.test
-gcc.compile.c++ ../../../../../bin.v2/libs/assign/v2/test/unit_testing/anon.test/gcc-4.4.3/debug/anon.o
-gcc.link ../../../../../bin.v2/libs/assign/v2/test/unit_testing/anon.test/gcc-4.4.3/debug/anon
-testing.capture-output ../../../../../bin.v2/libs/assign/v2/test/unit_testing/anon.test/gcc-4.4.3/debug/anon.run
-**passed** ../../../../../bin.v2/libs/assign/v2/test/unit_testing/anon.test/gcc-4.4.3/debug/anon.test
 gcc.compile.c++ ../../../../../bin.v2/libs/assign/v2/test/unit_testing/chain.test/gcc-4.4.3/debug/chain.o
 ../../../../../boost/assign/v2/chain/checking/twin_values.hpp: In function ‘void boost::assign::v2::checking::chain::twin_values::do_check() [with T = int]’:
 ../../../../../boost/assign/v2/chain/checking/twin_values.hpp:157: warning: ‘a1’ may be used uninitialized in this function
@@ -46,5 +35,50 @@ In file included from ref.cpp:20:
 ../../../../../libs/assign/v2/test/ref/fusion_matrix.cpp:112: warning: unused variable ‘row’
 gcc.link ../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref
 testing.capture-output ../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.run
-**passed** ../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.test
-...updated 32 targets...
+====== BEGIN OUTPUT ======
+ref: ../../../../../libs/assign/v2/test/ref/fusion_matrix.cpp:110: void test_assign_v2::xxx_ref::xxx_fusion_matrix::test(): Assertion `row.static_elem(boost::mpl::int_<0>() ) == 2' failed.
+Running 6 test cases...
+unknown location(0): fatal error in "xxx_fusion_matrix::test": signal: SIGABRT (application abort requested)
+
+*** 1 failure detected in test suite "Master Test Suite"
+
+EXIT STATUS: 201
+====== END OUTPUT ======
+
+    LD_LIBRARY_PATH=/usr/bin:/usr/lib:/usr/lib32:/usr/lib64:$LD_LIBRARY_PATH
+export LD_LIBRARY_PATH
+
+     "../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref"   > "../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.output" 2>&1
+    status=$?
+    echo >> "../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.output"
+    echo EXIT STATUS: $status >> "../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.output"
+    if test $status -eq 0 ; then
+        cp "../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.output" "../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.run"
+    fi
+    verbose=0
+    if test $status -ne 0 ; then
+        verbose=1
+    fi
+    if test $verbose -eq 1 ; then
+        echo ====== BEGIN OUTPUT ======
+        cat "../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.output"
+        echo ====== END OUTPUT ======
+    fi
+    exit $status
+
+...failed testing.capture-output ../../../../../bin.v2/libs/assign/v2/test/unit_testing/ref.test/gcc-4.4.3/debug/ref.run...
+gcc.compile.c++ ../../../../../bin.v2/libs/assign/v2/test/unit_testing/type_traits.test/gcc-4.4.3/debug/type_traits.o
+gcc.link ../../../../../bin.v2/libs/assign/v2/test/unit_testing/type_traits.test/gcc-4.4.3/debug/type_traits
+testing.capture-output ../../../../../bin.v2/libs/assign/v2/test/unit_testing/type_traits.test/gcc-4.4.3/debug/type_traits.run
+**passed** ../../../../../bin.v2/libs/assign/v2/test/unit_testing/type_traits.test/gcc-4.4.3/debug/type_traits.test
+gcc.compile.c++ ../../../../../bin.v2/libs/assign/v2/test/unit_testing/detail.test/gcc-4.4.3/debug/detail.o
+gcc.link ../../../../../bin.v2/libs/assign/v2/test/unit_testing/detail.test/gcc-4.4.3/debug/detail
+testing.capture-output ../../../../../bin.v2/libs/assign/v2/test/unit_testing/detail.test/gcc-4.4.3/debug/detail.run
+**passed** ../../../../../bin.v2/libs/assign/v2/test/unit_testing/detail.test/gcc-4.4.3/debug/detail.test
+gcc.compile.c++ ../../../../../bin.v2/libs/assign/v2/test/unit_testing/anon.test/gcc-4.4.3/debug/anon.o
+gcc.link ../../../../../bin.v2/libs/assign/v2/test/unit_testing/anon.test/gcc-4.4.3/debug/anon
+testing.capture-output ../../../../../bin.v2/libs/assign/v2/test/unit_testing/anon.test/gcc-4.4.3/debug/anon.run
+**passed** ../../../../../bin.v2/libs/assign/v2/test/unit_testing/anon.test/gcc-4.4.3/debug/anon.test
+...failed updating 1 target...
+...skipped 1 target...
+...updated 30 targets...
